#!/bin/bash

. is-git-repo.sh

FROM="${1:-master}"
TOO="${2:-HEAD}"

BRANCH=`git rev-parse --abbrev-ref $TOO 2>&1`

if [ $FROM != 'master' ]
then
  FROM="$FROM^"
fi

echo "Pushing from $FROM to $TOO"
git log --pretty=format:%H --reverse "$FROM..$TOO" | xargs -I{} git push -f origin {}:"$BRANCH"

