#!/bin/sh

FROM="${1:-master}"
TOO="${2:-HEAD}"

BRANCH=`git rev-parse --abbrev-ref $TOO`

if [ $FROM != 'master' ]
then
  FROM="$FROM^"
fi

if [ $? -eq 0 ]
then
  echo "Displaying from $FROM to $TOO"
  git log --pretty=format:%H --reverse "$FROM..$TOO" | xargs -I{} echo git push -f origin {}:"$BRANCH"
else
  echo "I dont think this is a git repo!"
fi
