#!/bin/bash

. is-git-repo.sh

TARGET_BRANCH="$1"
CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD 2>&1`

git checkout "$TARGET_BRANCH"
git pull
git checkout "$CURRENT_BRANCH"
git rebase "$TARGET_BRANCH"
